# Generated by Django 5.0.4 on 2024-05-02 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_users', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, max_length=100, null=True)),
                ('project_cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_category_add', models.CharField(blank=True, max_length=100, null=True)),
                ('material_works', models.CharField(blank=True, max_length=100, null=True)),
                ('material_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('material_quandity', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projectsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='LabourDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_category_add', models.CharField(blank=True, max_length=100, null=True)),
                ('labour_works', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projectsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_category_add', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_works', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('aditional_quandity', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projectsdetails')),
            ],
        ),
    ]
