# Generated by Django 5.0.4 on 2024-05-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_projectsdetails_materialsdetails_labourdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsdetails',
            name='project_cost_paid',
            field=models.IntegerField(null=True),
        ),
    ]
