# Generated by Django 5.0.4 on 2024-05-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_projectsdetails_project_cost_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourdetails',
            name='mydate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labourdetails',
            name='qut',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
