# Generated by Django 5.0.4 on 2024-05-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_labourdetails_mydate_labourdetails_qut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsdetails',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
