# Generated by Django 5.0.4 on 2024-05-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_projectsdetails_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsdetails',
            name='at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
