# Generated by Django 5.0.4 on 2024-05-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_projectsdetails_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mypassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
