# Generated by Django 5.0.4 on 2024-05-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_customuser_mypassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activate',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, null=True),
        ),
    ]
