# Generated by Django 5.0.4 on 2024-05-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_customuser_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='myactivate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
