# Generated by Django 5.0.4 on 2024-05-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_customuser_myactivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
