# Generated by Django 5.0.4 on 2024-05-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customuser_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='myactivate',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.CharField(blank=True, default='active', max_length=100, null=True),
        ),
    ]
